export enum RvBasicType {
  TEXT = 'TEXT',
  CUBE = 'CUBE',
  SPHERE = 'SPHERE',
  CONE = 'CONE',
  PRISM = 'PRISM',
  POLYHEDRON = 'POLYHEDRON',
  TORUS = 'TORUS',
  CYLINDER = 'CYLINDER',
  ICO_SPHERE = 'ICO_SPHERE',
  CAPSULE = 'CAPSULE',
  PLANE = 'PLANE',
}
