
export enum Operate {
  UNKNOWN = 'UNKNOWN',
  GLOBAL_INFORMATION_TITLE = 'GLOBAL_INFORMATION_TITLE',
  GLOBAL_INFORMATION_DESCRIPTION = 'GLOBAL_INFORMATION_DESCRIPTION',
  GLOBAL_INFORMATION_TAGS = 'GLOBAL_INFORMATION_TAGS',
}
