
export enum Operate {
  UNKNOWN = 'UNKNOWN',

  GLOBAL_INFORMATION_TITLE = 'GLOBAL_INFORMATION_TITLE',
  GLOBAL_INFORMATION_DESCRIPTION = 'GLOBAL_INFORMATION_DESCRIPTION',
  GLOBAL_INFORMATION_TAGS = 'GLOBAL_INFORMATION_TAGS',
  GLOBAL_SUPPORT_VR = 'GLOBAL_SUPPORT_VR',
  GLOBAL_SUPPORT_AR = 'GLOBAL_SUPPORT_AR',
  GLOBAL_SUPPORT_MR = 'GLOBAL_SUPPORT_MR',
  GLOBAL_SUPPORT_HP = 'GLOBAL_SUPPORT_HP',
  GLOBAL_PLAYING_AUTO = 'GLOBAL_PLAYING_AUTO',
  GLOBAL_PLAYING_LOOP = 'GLOBAL_PLAYING_LOOP',
  GLOBAL_PLAYING_INTERVAL = 'GLOBAL_PLAYING_INTERVAL',


}
